apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: devops6app
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://127.0.0.1:6443
    stage:
      defaultNamespace: stage
      server: https://127.0.0.1:6443
      excludes:
        - endpoint
    prod:
      defaultNamespace: prod
      server: https://127.0.0.1:6443
      includes:
        - endpoint
  vars: {}
  excludes:
    - services
    - ingress